### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Jok3rTV** [AdvancedPlugins/AdvancedMobs#1]
Add the option on Spawners Upgrades to change the mobs drops at few levels
Example:
Skeleton LvL 1 - Bone Meal
Skeleton LvL 5 - Bone
Skeleton LvL 10 - Bone Block

**Comment by GC-spigot** [comment]
You can do that with drops already, just specify at which levels those drops only applicable forOn 2022-11-06, at 01:50 AM, feliz ***@***.***> wrote:﻿
Add the option on Spawners Upgrades to change the mobs drops at few levels
Example:
Skeleton LvL 1 - Bone Meal
Skeleton LvL 5 - Bone
Skeleton LvL 10 - Bone Block
