### ISSUE TITLE
Add whitelist mode for mob stacking

### ISSUE THREAD

**Issue by ArmonicPvP** [AdvancedPlugins/AdvancedMobs#10]
Make it so you can whitelist spawn events and mob types instead of blacklist. If I only want Blazes to stack from spawners, I have to blacklist every single spawn event and every single mob EXCEPT blazes and spawner.

**Comment by GC-spigot** [comment]
Plugin only stacks mobs from spawners. I'm adding a setting for next update to turn the blacklist into whitelist
