### ISSUE TITLE
Plugin error

### ISSUE THREAD

**Issue by costin33l** [AdvancedPlugins/AdvancedMobs#13]
![image](https://user-images.githubusercontent.com/115091731/204085658-826e70dd-5130-43c0-9acc-d7eace821d3f.png)
it literally gives me this error anytime i want to type a command from the plugin.

**Comment by GC-spigot** [comment]
Please include your server latest.log fileOn 2022-11-26, at 01:09 PM, costin33l ***@***.***> wrote:﻿

it literally gives me this error anytime i want to type a command from the plugin.

**Comment by GC-spigot** [comment]
Can you show your logs file? Plugin is disabling itself
