### ISSUE TITLE
Deleted spawner leaving spawner name text and continuing to spawn when removed - [Issue] 

### ISSUE THREAD

**Issue by MODNMETL** [AdvancedPlugins/AdvancedMobs#14]
### Describe the bug

When a mammoth spawner was destroyed its label text remained behind and it continued to spawn even after doing a /killall command. We had to do a server restart to clear the text and stop the spawning.

### How to reproduce

Paper 1.19.2 place spawner, watch mammoth appear. In creative mode destroy spawner by breaking and do /killall and watch them continue to appear from the point where the spawner was

BTW the screenshot is actually from another user in your discord who posted the same issue about the text they were having, so I've attached that to this issue report as I didn't have a screenshot of ours, but the problem was still the same, albeit the text on ours only showed the one instance, whereas theirs shows 3

### Screenshots / Videos

https://prnt.sc/aB-y3Ri8t_OF

### Server Log

https://mcpaste.io/143ccbaf77d024f4

**Comment by GC-spigot** [comment]
Fixed! Was a problem with creative mode
