### ISSUE TITLE
Bug in game

### ISSUE THREAD

**Issue by Jeyde** [AdvancedPlugins/AdvancedMobs#16]
### Describe the bug

Hi, 

I tried to use your plugin in different ways. The display function is working but the egg or the spawner aren't. I mean, I see Armor stands bugging (on/off repetitively with animals sounds). It's the same for natural spawns. And for some reason, the raptor was visible but I didn't test any mob. For example the flamingo or the red panda weren't. I put my log file. Can it be an issue with another plugin or datapack? 

Thanks in advance

### How to reproduce

I was in game, just putting a spawner or using an egg I got from commands. But mobs didn't appear properly.

### Server Log

https://mcpaste.io/56e42957a803ff1e

**Comment by GC-spigot** [comment]
Can you record a gif / video of this behavior? It's likely something conflicting

**Comment by Jeyde** [comment]
I don't have the video at the moment but I've just found out that it only occurs when the game difficulty was peaceful. I have no issue in other modes, so I guess that's ok as at the end, my server will not be in peaceful mode.

**Comment by GC-spigot** [comment]
Ok, thanks for information.
