### ISSUE TITLE
[Issue] a lof of bugs with spawner

### ISSUE THREAD

**Issue by AndrzejPL** [AdvancedPlugins/AdvancedMobs#18]
### Describe the bug

when i put my spawner from epicspawners its SPAWNER PIG? REALLY? a lot of bugs i pay for it 15$
and other bug is imporant repair worldguard region can players break spawner ?? REALLY?? My players break spawners in region

### How to reproduce

when i put my spawner from epicspawners its SPAWNER PIG? REALLY? a lot of bugs i pay for it 15$
and other bug is imporant repair worldguard region can players break spawner ?? REALLY?? My players break spawners in region

**Comment by GC-spigot** [comment]
Epicspawners is not supported, it’s literally said on the plugin page. This replaces any other spawner plugin…On 2022-12-21, at 08:11 PM, AndrzejPL ***@***.***> wrote:﻿
Describe the bug
when i put my spawner from epicspawners its SPAWNER PIG? REALLY? a lot of bugs i pay for it 15$
and other bug is imporant repair worldguard region can players break spawner ?? REALLY?? My players break spawners in region
How to reproduce
when i put my spawner from epicspawners its SPAWNER PIG? REALLY? a lot of bugs i pay for it 15$
and other bug is imporant repair worldguard region can players break spawner ?? REALLY?? My players break spawners in region
Screenshots / Videos
No response
Server Log
No response

**Comment by AndrzejPL** [comment]
please add option disable your spawners and spawn naturally only, or add support epicspawners and add support worldguard?
Players in my region on spawn can break SPAWNERS REALLY? i want to comeback my money when u don't reapir this

**Comment by AndrzejPL** [comment]
or give my code this plugin and i repair this and add support epicspawners is so easy, do u dont know ?

**Comment by AndrzejPL** [comment]
and can u add option disable your shit spawners is so easy

**Comment by GC-spigot** [comment]
Stop over reacting, this doesn’t help you or us. Sure we’ll look into it, epicspawners isnt much updated or used anymore - but we’ll make sure they work together :)On 2022-12-21, at 08:43 PM, AndrzejPL ***@***.***> wrote:﻿
or give my code this plugin and i repair this and add support epicspawners is so easy, do u dont know ?

**Comment by GC-spigot** [comment]
There’s a setting in config already. Why are you cursing lolOn 2022-12-21, at 08:45 PM, AndrzejPL ***@***.***> wrote:﻿
and can u add option disable your shit spawners is so easy

**Comment by AndrzejPL** [comment]
Can u repair now break spawners in worldguard region? Its easy.

**Comment by AndrzejPL** [comment]
Where is option disable your SPAWNERS? i dont see in config add this now

**Comment by AndrzejPL** [comment]
i see only spawnerStacking:
  # Is spawner stacking enabled?
  enabled: false 
  this dosent disable your SPAWNERS!!!!

**Comment by AndrzejPL** [comment]
add option disable your spawners now, i don't want your looser spawners so dosent work i want only mobs

**Comment by AndrzejPL** [comment]
15$ for this? never again when u don't help me

**Comment by GC-spigot** [comment]
What’s your problem? How are you so entitled, chill and wait for next update, you already listed all of your issues, go do something productive instead.On 2022-12-21, at 08:53 PM, AndrzejPL ***@***.***> wrote:﻿
15$ for this? never again when u don't help me

**Comment by AndrzejPL** [comment]
i don't have time i buy this plugin for my players so dosent work? i pay?!!!
this issue its repair about 5 minus for me.

**Comment by AndrzejPL** [comment]
when u update this ?

**Comment by GC-spigot** [comment]
Just wait for next update like all people do, it's going to be fixed first thing tomorrow. My computer's in my office and I'm at home now.

**Comment by AndrzejPL** [comment]
okay i waiting for update, add option all disable spawners, fix worldguard region break spawners, and if u do add epicspawners supprot or add option disable your spawners!

see u tomorrow moring.

**Comment by GC-spigot** [comment]
Added, wait for next update

**Comment by AndrzejPL** [comment]
i am waiting for update? now is moring hm?

**Comment by GC-spigot** [comment]
Dude, what's your problem? Stop being so entitled, people like you ruin this game.
Update will be out when i update it.

**Comment by AndrzejPL** [comment]
Baby you say i update tomorrow moring, now is tomorrow moring :)

**Comment by AndrzejPL** [comment]
Today is updated?

**Comment by AndrzejPL** [comment]
Thanks for update, can u add will soon api to yours spawners? etc i want create my own spawners
