### ISSUE TITLE
[Issue] Plugin literally not working

### ISSUE THREAD

**Issue by FluxBoys** [AdvancedPlugins/AdvancedMobs#23]
### Describe the bug

• The plugin doesn't work properly at all, Sometimes the random spawns work (kinda) and sometimes it doesn't work at ALL

• Another issue is that you are REQUIRED to have vanilla mobs spawned to have custom mobs spawn aswell which is super dumb what is the point of custom mobs if you gotta have vanilla mobs spawn aswell?

• The plugin is HELLA buggy and whenever the random spawns work it spawns mobs that I REMOVED from the config and YES I did reload the plugin...

I'm very very disappointed in the plugin its not what I expected at all

### How to reproduce

The description should epxlain it

**Comment by GC-spigot** [comment]
What do you mean by "kinda works"? It's not supposed to replace every mob in the world, not designed to do so. It's designed to mix in with vanilla mobs, however we're adding a setting soon to disable vanilla mob spawning.
If a value doesn't update, try restarting. Removing mobs from randomSpawning.yml allowed list does work and we just tested it.
