### ISSUE TITLE
Bow + Arrow breaks loot tables

### ISSUE THREAD

**Issue by 0SaurFeng** [AdvancedPlugins/AdvancedMobs#24]
### Describe the bug

Upon hitting a mob (my version: Vindicator) with a bow, their loottable breaks, and no drops are received from them, nor McMMO exp. No drops come after hitting them with a single arrow.

### How to reproduce

Shoot a mob that was produced from a spawner with a bow (arrow).

### Server Log

https://mcpaste.io/fe299342e07a0ea5

**Comment by GC-spigot** [comment]
Is this only the case with Vindicator? I'm using the latest mcmmo + advancedmobs: https://gyazo.com/b3aabfbe4782ab6a79b0afb0df54d7f3
