### ISSUE TITLE
[Issue] DESTORY SPAWNER IN REGION WORLDGAURD

### ISSUE THREAD

**Issue by AndrzejPL** [AdvancedPlugins/AdvancedMobs#25]
### Describe the bug

please repair this now, my players breaks spawners in my region on spawn!!! REPAIR THIS NOW!

### How to reproduce

please repair this now, my players breaks spawners in my region on spawn!!! REPAIR THIS NOW!

**Comment by Awpmeister2170** [comment]
No ETA but it's high on the list of priority fixes, we will inform you when the update is pushed.

**Comment by GC-spigot** [comment]
@AndrzejPL Give some information, like what region plugin you are using, AdvancedMobs version and server version.

**Comment by GC-spigot** [comment]
https://gyazo.com/c9828c9ceb900dba2879470c5c6ad4fa

**Comment by AndrzejPL** [comment]
i say worldguard plugin and advancedmobs last version

**Comment by GC-spigot** [comment]
I cannot recreate it, this is working fine for me and everyone else that has been asked to test it.
