### ISSUE TITLE
[Issue]Plugin is constantly giving errors in console, plugin seems to work as expected though 

### ISSUE THREAD

**Issue by xskrillex** [AdvancedPlugins/AdvancedMobs#28]
### Describe the bug

I'm constantly getting the same error (every few seconds) in console

### How to reproduce

1. Download & Install this plugin
2. Download & install superiorskyblock

### Server Log

https://pastebin.com/FjwyTbp7

**Comment by GC-spigot** [comment]
This is an issue with SuperiorSkyblock2! :)
