### ISSUE TITLE
Spawner holograms stay after spawner is broken

### ISSUE THREAD

**Issue by aXe18** [AdvancedPlugins/AdvancedMobs#29]
### Describe the bug

Well Spawner holograms stay after spawner is broken :D

### How to reproduce

At least happening on 1.19.2 and latest Am version so 1.2.5
Check more from ticket amobs-0030 and/or from Awpmeister :) 

### Screenshots / Videos

![Screenshot_799](https://user-images.githubusercontent.com/26152540/216442957-78f7ea03-ce3a-450e-9a84-e00bb6c5909e.png)

**Comment by cubilization** [comment]
I used the Minecraft kill command to solve this on my server

Using this command ingame: **/minecraft:kill @e[type=armor_stand,distance=..3]**

Change the Distance '3' as required

**Comment by wonderousduck** [comment]
Happened for me on 1.19.3
Above fixes it
Seems like the armor stands aren't being removed with the spawners every so often

**Comment by GC-spigot** [comment]
Can ya'll check console for errors? I'm not able to recreate this and would like for it to be fixed!

**Comment by JakeusCakeus** [comment]
I'm getting this issue too, although I can't remove the armor stand. I also can't see anything in the console on my end
