### ISSUE TITLE
[Issue] with WholeStackDeath on Stacks not Multiplying XP

### ISSUE THREAD

**Issue by wonderousduck** [AdvancedPlugins/AdvancedMobs#31]
### Describe the bug

I tested with and without wholeStackDeath config on
Version tested on 1.19.3

Found that xp would just give a single zombie amount not matter stack size
Mob loot multiplies as normal
This must be a bug can you please fix this as this is the only feature I bought the plugin for

### How to reproduce

Test how much xp received from large mob stacks with this setting on and off

**Comment by wonderousduck** [comment]
No server log as is not needed no errors received at all

This log occurs when I kill a large stack but nothing lookss wrong in it:

[14:08:39] [Server thread/INFO]: Named entity EntityZombie['ZOMBIE x141'/21126, uuid='a3e03a53-6ce6-4288-971c-c3e52456a9dd', l='ServerLevel[world]', x=-1000346.70, y=-19.50, z=-1000366.30, cpos=[-62522, -62523], tl=156, v=true] died: ZOMBIE x141 was slain by Duck424

I wonder if adding stack xp multiplier config option would help with this issue?

**Comment by GC-spigot** [comment]
Why did you open a chargeback immediately? What is the appropriate time to wait before opening one? I have been away on a vacation where there is no signal, how do you expect for me to respond?

**Comment by wonderousduck** [comment]
Hello

Because I bought a plugin for stacking and it didn't work as xp wasn't
scaling to stack at all.
I'm sorry you were on vacation i was not aware. I raised tickets about this
and raised an was told to raise an issue on github but wasn't finding a
response. I only have a small server friends server and have since switched
to another free plugin that is working. as I can't use the plugin I was
trying to request my money back.

also thank you for your response while you were on holiday.

My apologies

**Comment by GC-spigot** [comment]
This is a very simple issue to fix - will be fixed asap :)
