### ISSUE TITLE
[Issue] Some of the effects are bugged

### ISSUE THREAD

**Issue by ShockCharge** [AdvancedPlugins/AdvancedMobs#33]
### Describe the bug

![image](https://user-images.githubusercontent.com/48907444/217011267-14dec4d9-1baf-41df-bc46-2340940695bc.png)
![image](https://user-images.githubusercontent.com/48907444/217011413-2791cdb7-93ca-4f51-b254-c05e9a004a58.png)
![image](https://user-images.githubusercontent.com/48907444/217010736-9d62ee70-3a9f-4595-8969-b58423b7a1b7.png)
![image](https://user-images.githubusercontent.com/48907444/217011604-8f65a377-5dc7-4dfb-a105-ab59d244f1d4.png)
![image](https://user-images.githubusercontent.com/48907444/217011047-21c0f9f1-99e4-4569-bca4-f905695bedf9.png)

### How to reproduce

N/A

### Screenshots / Videos

N/A

**Comment by GC-spigot** [comment]
Thanks for reporting, we will be looking into it. New effects system is super new and will have issues.
