### ISSUE TITLE
Spawners dont accept VAULT as currency

### ISSUE THREAD

**Issue by aXe18** [AdvancedPlugins/AdvancedMobs#34]
### Describe the bug

Try change EXP to VAULT at spawner upgrades

### How to reproduce

Versions 1.2.6 and 1.2.7 at least have this issue. And when its vault it gives an error

### Screenshots / Videos

https://pastebin.com/gfsZxKH1

**Comment by GC-spigot** [comment]
It's `MONEY` not `VAULT`
