### ISSUE TITLE
Premium Mobs not spawning properly

### ISSUE THREAD

**Issue by backlot** [AdvancedPlugins/AdvancedMobs#37]
### Describe the bug

I created a blank new server. I uploaded two plugins: AdvancedMobs and ModelEngine. Regular mobs spawn fine with the /am mob command, but the premium mobs don't. They appear for a brief instant, then die. I uploaded them to the "included" file, as that is where the other .bbmodel files were. However, even the otter which came with the advancedmobs plugin won't spawn. It too, dies. Why is this?

### How to reproduce

I type /am mob mammoth to spawn the mammoth. It dies the moment it spawns. Same goes for all other .bbmodel files.

### Screenshots / Videos

https://imgur.com/a/AWGgVIl

https://imgur.com/a/OwBg5ag

**Comment by aXe18** [comment]
Ticket amobs-0051

**Comment by Awpmeister2170** [comment]
This sounds like you haven’t got the Resourse Pack installed correctly, best to look up on YouTube how a resoursepack works so you know how to install it. 

Do you have any errors in console regarding these mobs when attempting to spawn them?

**Comment by backlot** [comment]
In the ticket amobs-0051 I put all the screenshots of the error messages. Would you like me to post them here as well? Also...it's a resource pack??? I thought it was a plugin 🤦‍♂️

**Comment by backlot** [comment]
Regular mobs spawn just fine when I use the command

**Comment by backlot** [comment]
![Screenshot_20230228-225448~2](https://user-images.githubusercontent.com/15160779/222041195-80e21cfc-7ebc-4f28-8d33-a282d3dd71fb.png)

Here it says it's not a resource pack in the description

**Comment by Awpmeister2170** [comment]
The Premium Mob Pack is made Via Model-engine

 ![image](https://user-images.githubusercontent.com/45782230/222114148-53285956-8541-4cf2-8f28-9e87dafda957.jpeg)

**Comment by backlot** [comment]
Mmm ok. What should I do with the otter? It's also a .bbmodel file like the premium mobs, but it comes with the advanced mobs plugin and immediately dies upon spawning
