### ISSUE TITLE
[Issue] add option disable holograms spawner

### ISSUE THREAD

**Issue by AndrzejPL** [AdvancedPlugins/AdvancedMobs#39]
### Describe the bug

add option disable holograms spawner please

### How to reproduce

add option disable holograms spawner

**Comment by GC-spigot** [comment]
Will add soon!

**Comment by AndrzejPL** [comment]
i am waiting

**Comment by AndrzejPL** [comment]
where add you? its imporant holograms lagg minecraftt servever i want remove this shit

**Comment by AndrzejPL** [comment]
> Will add soon!

i still waiting when u add ? i have 6k armorstand from your plugin its so laggy
