### ISSUE TITLE
Console spam

### ISSUE THREAD

**Issue by aXe18** [AdvancedPlugins/AdvancedMobs#40]
### Describe the bug

Well sometimes and kinda often console gets spammed whit "Could not pass event EntityDamageByEntityEvent to AdvancedMobs v1.3.0" Does not affect to the plugin, it works and all, this issue has been on previous versions but now in 1.3.0 it comes more often. I dont mind spams, but it makes console so messy that i cant read anything else from there 

### How to reproduce

Well, i dont know :D Download plugin and let server run some time and players play, it comes eventually

### Screenshots / Videos

![Screenshot_1056](https://user-images.githubusercontent.com/26152540/222481227-ccbc3259-e4dd-4219-a4b3-7c7274700235.png)

**Comment by AndrzejPL** [comment]
i have the same fix this error now!!!

**Comment by GC-spigot** [comment]
> ### Describe the bug
> Well sometimes and kinda often console gets spammed whit "Could not pass event EntityDamageByEntityEvent to AdvancedMobs v1.3.0" Does not affect to the plugin, it works and all, this issue has been on previous versions but now in 1.3.0 it comes more often. I dont mind spams, but it makes console so messy that i cant read anything else from there
> 
> ### How to reproduce
> Well, i dont know :D Download plugin and let server run some time and players play, it comes eventually
> 
> ### Screenshots / Videos
> ![Screenshot_1056](https://user-images.githubusercontent.com/26152540/222481227-ccbc3259-e4dd-4219-a4b3-7c7274700235.png)
> 
> ### Server Log
> _No response_

Could you attach server logs or PM me on discord them?
