### ISSUE TITLE
[Issue] Well Spawner holograms stay after spawner is broken

### ISSUE THREAD

**Issue by AndrzejPL** [AdvancedPlugins/AdvancedMobs#45]
### Describe the bug

Well Spawner holograms stay after spawner is broken 
PLEASE REPIAR THIS AND ADD OPTION DISABE HOLOGRAMS SPAWNER

### How to reproduce

PLEASE REPIAR THIS AND ADD OPTION DISABE HOLOGRAMS SPAWNER

### Screenshots / Videos

Well Spawner holograms stay after spawner is broken

**Comment by GC-spigot** [comment]
Added
