### ISSUE TITLE
[Issue] advancedenchanteents

### ISSUE THREAD

**Issue by AndrzejPL** [AdvancedPlugins/AdvancedMobs#47]
### Describe the bug

hello
help me developer
i buy advancedenchantments
and so lagging this
net.advancedplugins.ae.enchanthandler.enchanttypes.MINING.onBlockBreak()
this event is so lagging
so can u add disable this event in config file ?
please its imporant for me
add option disable this event in config file
i dont have mining enchantemnts and lagg so ..?

### How to reproduce

hello
help me developer
i buy advancedenchantments
and so lagging this
net.advancedplugins.ae.enchanthandler.enchanttypes.MINING.onBlockBreak()
this event is so lagging
so can u add disable this event in config file ?
please its imporant for me
add option disable this event in config file
i dont have mining enchantemnts and lagg so ..?

**Comment by GC-spigot** [comment]
No one else (2400+ servers) is having lag soo??
