### ISSUE TITLE
BUG on Fresh Install 04-05-2023

### ISSUE THREAD

**Issue by HighPriestKing** [AdvancedPlugins/AdvancedMobs#49]
### Describe the bug

WARN error on fresh install of the plugin. Running 1.19.3 all premium and up to date, some dev builds for certain things here and there.

---

[06:18:53 WARN]: java.util.NoSuchElementException: No value present

---

### How to reproduce

fresh install of Advanced Mobs, im also using Advanced Pets & Premium Mobs

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/103746871/230055345-b539bc7c-bea9-4a44-860a-6acd77c95ab2.png)

![image](https://user-images.githubusercontent.com/103746871/230055462-f47d20a8-3841-40a7-9486-08e8d25024fd.png)

**Comment by GC-spigot** [comment]
Fixed
