### ISSUE TITLE
Conflict between two entries

### ISSUE THREAD

**Issue by aXe18** [AdvancedPlugins/AdvancedMobs#54]
### Describe the bug

plugin is attempting to create an ImmutableMap of these key-value pairs, but is encountering an error due to the conflict.
https://pastebin.com/0FHSKgT3

### How to reproduce

Latest Amobs and just start server

### Screenshots / Videos

https://pastebin.com/0FHSKgT3

**Comment by GC-spigot** [comment]
Fixed!
