### ISSUE TITLE
[Issue] Plugin dont work with "Lands" Plugin

### ISSUE THREAD

**Issue by 9quhh** [AdvancedPlugins/AdvancedMobs#59]
### Describe the bug

Script error and dont start.

### How to reproduce

Start the Script with the Script "Lands" activated.

### Screenshots / Videos

https://media.discordapp.net/attachments/1127274721508077669/1127697811874517112/image.png?width=810&height=455

**Comment by aXe18** [comment]
Could this taken look into ?

**Comment by TheDelusioned** [comment]
Still an issue with release 1.5.5...  Just purchased this plugin and cannot use it currently.  Please help.
![image](https://github.com/AdvancedPlugins/AdvancedMobs/assets/26825501/12cbeeb6-e780-419f-a6a0-47767d61322f)
