### ISSUE TITLE
Internal error when trying to obtain a mob that doesn't exist.

### ISSUE THREAD

**Issue by sarhatabaot** [AdvancedPlugins/AdvancedMobs#7]
Not so much an issue as a QoL improvement. 
If I try and obtain a mob that doesn't exist, (if I mi-spelt a mob name for an example)
The plugin throws up a "An internal error occurred while attempting to perform this command".

Instead of the error the plugin should probably send a message to the user "This mob does not exist" or something like that.

**Comment by GC-spigot** [comment]
Fixed :)
