### ISSUE TITLE
I would like to know how can i make the customentityinstance follow the player  using the advancedmobs api.

### ISSUE THREAD

**Issue by BletzziDev** [AdvancedPlugins/AdvancedMobs#70]
### Describe the bug

I would like to know how can i make the customentityinstance follow the player  using the advancedmobs api.

### How to reproduce

I tried the setOwnerIGN  method but doesn't works.

**Comment by GC-spigot** [comment]
We're using a silverfish as a base mob and just setting it's target that way.
