### ISSUE TITLE
Stacked spawners become a single one after /am reload

### ISSUE THREAD

**Issue by ItsOn3x** [AdvancedPlugins/AdvancedMobs#72]
### Describe the bug

If i stack, exmaple: 10 Iron Golem spawners in one stack, reload the plugin (/am reload), and then break it, it drops one spawner in level 0. Server Version: 1.19.4
Also, as shown in the video, holograms does not dissapear.
I have removed all plugins and re-installed that can be related to holograms interfering.

### How to reproduce

I guess i have reproduced it already, above.

### Screenshots / Videos

https://we.tl/t-8U84FHQErn

- WeTransfer Link

### Server Log

https://mcpaste.io/2b388655458ae5b3

**Comment by GC-spigot** [comment]
Fixed!
