### ISSUE TITLE
[Issue] It kicks from the server

### ISSUE THREAD

**Issue by Volsira** [AdvancedPlugins/AdvancedMobs#77]
### Describe the bug

It kicks me out of the game after a certain amount of time while fighting the vanilla mob. Average time is 10 minutes.

### How to reproduce

I have nothing additional to point out. I'm having problems when I fight vanilla monsters.

### Screenshots / Videos

![Ekran görüntüsü 2024-01-05 172716](https://github.com/AdvancedPlugins/AdvancedMobs/assets/155748745/9b868dc0-1227-4e8e-9913-12759c5b5749)

### Server Log

https://mclo.gs/prV2oBF

**Comment by GC-spigot** [comment]
Thanks we're looking into this!
