### ISSUE TITLE
Mobs not spawning/immediately turning invisible

### ISSUE THREAD

**Issue by Zero-Escape** [AdvancedPlugins/AdvancedMobs#8]
I am using a AdvancedMobs to generate new mobs throughout my world. On my server Im using multiverse to have multiple worlds. On the worlds using a world/biome generator that is not vanilla the mobs seemingly spawn but imediately turn invisible. I verified that the plugin works perfectly on the overworld that uses vanilla generation but on the world generated using Stratos or VoidGen the mobs are invisible. I can see them, flash into existance every 3 seconds or so for a split second and they can be hit with a sword. But other than that they cant be seen. Displays are invisible too.
Confirmed that vanilla armor stands work perfectly fine.

Plugins in use(49): 
ActionHealth, AdvancedMobs, AdvancedRegionMarket, AngelChest, ArmoredElytra, AureliumSkills, Chunky, CustomPortals*, DailyRewards, DeluxeHub, DeluxeMenus, DiscordSRV, Essentials, EssentialsChat, EssentialsSpawn, ExcellentCrates, FastAsyncWorldEdit (WorldEdit), floodgate, Geyser-Spigot, GriefPrevention, HeadsPlus, HoloRemove*, InteractionVisualizer, LibsDisguises, LuckPerms, MiniaturePets, MoneyFromMobs, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, Multiverse-Portals, MythicMobs, NexEngine, PlaceholderAPI, ProtocolLib, Randomtp, SafariNet, ServersNPC, Shop, SinglePlayerSleep, Stratos, TAB, TimeIsMoney, Vault, ViaBackwards, ViaVersion, VoidGen, WorldEditSelectionVisualizer, WorldGuard

**Comment by GC-spigot** [comment]
So it works fine from my testing, can you try removing some plugins and testing then? One of them is the issue
