### ISSUE TITLE
[Feature Request] Eco plugins support

### ISSUE THREAD

**Issue by BurningCoolDude** [AdvancedPlugins/AdvancedMobs#81]
### Describe the bug

Support for eco plugins to be used in mob drops and such (and as materials!).

### How to reproduce

Typically support is eco plugin name:itemname
Example:
ecoitems:amethyst_scythe

**Comment by GC-spigot** [comment]
They intentionally break our plugins instead of having a support, so until that's solved we're not going to be supporting them unfortunately.
