### ISSUE TITLE
[Suggestion] Option to disable sounds for players / lower volume

### ISSUE THREAD

**Issue by bobhenl** [AdvancedPlugins/AdvancedMobs#86]
### Describe the bug

Hi, I'd like to suggest features:
1. Option for players to disable mob sounds on their own. Cause for some it can be annoying.
2. A way to disable these sounds in specific regions
3. Or at least way to set the volume (yaw / pitch or how it's called) in the config / specific .mob files, or may even as command so players can control it on their own.

### How to reproduce

Some players are complaining that the sounds are so loud & they don't really like them, but they don't want to disable sounds in Minecraft settings due to it.

**Comment by GC-spigot** [comment]
Added configurable volume setting in config.yml :)
