### ISSUE TITLE
[Issue] FPS drops - way to reduce armor stands?

### ISSUE THREAD

**Issue by bobhenl** [AdvancedPlugins/AdvancedMobs#97]
### Describe the bug

Hello, could it be possible to add some performance options, or reduce armor stands a bit? I tried staring on spawn into the area without display of advanced mobs, and then to area with only 3 advanced mobs display, and it causes FPS drops due to the amount of armor stands used. Cannot it be reduced or somehow optimized? 

### How to reproduce

Just build some testing area with walls around you, then check your FPS. Then spawn mob using /am display MOB, maybe spawn 3 of them, like 3 flamingos or 2 monkeys or so... and you'll see that FPS drops, like I had 120-130 FPS and with 3 flamingos it dropped to like 100-110

**Comment by GC-spigot** [comment]
It's normal, we're working on converting from armorstands to display entities :)
